travis:
  secure:
    BINSTAR_TOKEN: pnDGQrgzBx9RYaPeg+kcuDl6iSzDTpiO0KItvLoi9A14/5gnz/zAZHlpTupUoJc/zk1nxSx0EQiQf2peZ6t6iq8lwx/tVSqtsjcdMgsJmi3m8v8yoHOgI09GpBtHhtWyAuYulbig+8l8fgWcz98XyFamrtmXqQYtJP8LymvFSinxaN4J9AgYIYkJw8tMpImgGBdDcjIxJPXu0onwZ8DbcfLxpUsf3NaXIjF9EIY+MR9xIsfuXubU+sQOVh71Xz0qQWrf8dug55qMycHYnWTFNkpv9Pq9ASP+1v5jDwPlp5sS7a7oG7E6KvloBQCOnPjjNNFEt4WygnnqC6C8j1crA1FMbO68Ok0xQmvIe6UAUBXDBZGVr80P3vFyhGTp840Eu4ovnX+vE7zxJWYwFx1Z1oaiGfHwBGKwQcgLmJFmWiCx6KITCO85H1n9/9hTZezatd33+Uvv+seJNA4y2yTn5gYSEy5JL51kFZZe/yCd2rjAlT///ZjiH2o5RIfHjdb7Po04fG9DkXzn1dzQMABbki+Qomgye5pM/quLQpbokv7RTqgviwNVI6CrMX7JsLry4fe+jYWDRDJvzFc158eDDtMAQyTH3M3XgFvxs9o10hdzyt7+G6GKkHZWmWYdW8EqODN5ZCnmAkyf6v9GL4+6YPOyorM1GQVa7iL+6QCa5Tw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
